# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyEmailUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, verbose_name=b'\xe9\x82\xae\xe7\xae\xb1')),
                ('code', models.CharField(max_length=6, verbose_name=b'\xe9\xaa\x8c\xe8\xaf\x81\xe7\xa0\x81')),
                ('category', models.SmallIntegerField(choices=[(0, b'\xe6\xb3\xa8\xe5\x86\x8c'), (1, b'\xe5\xbf\x98\xe8\xae\xb0\xe5\xaf\x86\xe7\xa0\x81')], default=0, verbose_name=b'\xe9\xaa\x8c\xe8\xaf\x81\xe7\xa0\x81\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('ip', models.CharField(max_length=20, verbose_name=b'\xe8\xaf\xb7\xe6\xb1\x82\xe6\x9d\xa5\xe6\xba\x90IP')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u90ae\u7bb1\u9a8c\u8bc1\u8bb0\u5f55',
                'verbose_name_plural': '\u90ae\u7bb1\u9a8c\u8bc1\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='VerifyMobileCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name=b'\xe6\x89\x8b\xe6\x9c\xba\xe5\x8f\xb7\xe7\xa0\x81')),
                ('code', models.CharField(max_length=6, verbose_name=b'\xe9\xaa\x8c\xe8\xaf\x81\xe7\xa0\x81')),
                ('category', models.SmallIntegerField(choices=[(0, b'\xe6\xb3\xa8\xe5\x86\x8c'), (1, b'\xe5\xbf\x98\xe8\xae\xb0\xe5\xaf\x86\xe7\xa0\x81')], default=0, verbose_name=b'\xe9\xaa\x8c\xe8\xaf\x81\xe7\xa0\x81\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('ip', models.CharField(max_length=20, verbose_name=b'\xe8\xaf\xb7\xe6\xb1\x82\xe6\x9d\xa5\xe6\xba\x90IP')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u624b\u673a\u9a8c\u8bc1\u8bb0\u5f55',
                'verbose_name_plural': '\u624b\u673a\u9a8c\u8bc1\u8bb0\u5f55',
            },
        ),
    ]
