# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 07:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', django_extensions.db.fields.UUIDField(blank=True, editable=False)),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='\u7528\u6237\u540d')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='\u90ae\u4ef6\u5730\u5740')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2016, 10, 11, 7, 29, 31, 464619), verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('real_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u771f\u5b9e\u59d3\u540d')),
                ('valid_email', models.BooleanField(default=False, verbose_name='\u662f\u5426\u9a8c\u8bc1\u90ae\u7bb1')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True, verbose_name='\u8bbe\u5907ID')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='\u8bbe\u5907Token')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'ordering': ['user'],
                'verbose_name': 'DeviceToken',
                'verbose_name_plural': 'DeviceToken',
            },
        ),
        migrations.AlterUniqueTogether(
            name='devicetoken',
            unique_together=set([('device_id', 'token')]),
        ),
    ]
