# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zqb_user', '0002_auto_20161011_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u6d3b\u8dc3'),
        ),
    ]
