# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 10:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zqb_user', '0004_auto_20161013_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdpartyOAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, verbose_name='\u4ee4\u724c')),
                ('partner', models.CharField(max_length=10, verbose_name='\u7b2c\u4e09\u65b9')),
                ('openid', models.CharField(max_length=50, verbose_name='openid')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'ordering': ['user'],
                'verbose_name': '\u7b2c\u4e09\u65b9\u7528\u6237\u7ed1\u5b9a',
                'verbose_name_plural': '\u7b2c\u4e09\u65b9\u7528\u6237\u7ed1\u5b9a',
            },
        ),
        migrations.AlterUniqueTogether(
            name='devicetoken',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='devicetoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='DeviceToken',
        ),
        migrations.AlterUniqueTogether(
            name='thirdpartyoauth',
            unique_together=set([('partner', 'openid')]),
        ),
    ]
